INSERT INTO karaoke_hub.Venue (name, address, city, state, zip_code, website, yelp_id)
VALUES
    ('7 Sky Bar', '3724 Northwest Loop 410', 'San Antonio', 'TX', '78229', 'https://7skybarlounge.com/', '7-sky-bar-san-antonio-2'),
    ('My House Lounge', '8075 Culebra Rd', 'San Antonio', 'TX', '78251', '', 'my-house-san-antonio'),
    ('Lion\'s Sports Bar', '4515 Fredericksburg Rd', 'Balcones Heights', 'TX', '78201', '', 'lions-sports-bar-san-antonio'),
    ('Dragon\'s Sports Bar', '1353 Bandera Rd', 'San Antonio', 'TX', '78228', '', 'official-dragons-sports-bar-san-antonio'),
    ('Joint Base Saloon', '5520 Randolph Blvd', 'San Antonio', 'TX', '78233', 'https://joint-base-saloon.business.site/', ''),
    ('Kennedy\'s Public House', '19179 Blanco Rd', 'San Antonio', 'TX', '78258', 'https://www.kennedysirishbar.com/', 'kennedys-public-house-san-antonio'),
    ('Doc Browns', '6511 TX-1604 Loop', 'San Antonio', 'TX', '78254', '', 'doc-browns-san-antonio-2'),
    ('Steely Nevada\'s Bar & Lounge', '7530 Bandera Rd', 'San Antonio', 'TX', '78238', '', 'steely-nevadas-san-antonio'),
    ('The Stetson Bar', '7350 Tezel Rd #108', 'San Antonio', 'TX', '78250', 'https://www.thestetsonbar.com/', 'the-stetson-bar-san-antonio'),
    ('The Stetson Dance Hall', '11881 Bandera Rd', 'Helotes', 'TX', '78023', 'https://www.stetsondancehall.com/', 'the-stetson-bar-san-antonio'),
    ('The Dooryard', '4503 De Zavala Rd Suite 108', 'San Antonio', 'TX', '78249', 'https://thedooryardsa.com/', 'the-dooryard-san-antonio'),
    ('Roxy\'s Keto Kitchen', '21025 Encino Commons Suite 114', 'San Antonio', 'TX', '78259', 'https://roxysketo.com/', 'roxy-s-keto-kitchen-san-antonio'),
    ('El Luchador Bar', '622 Roosevelt Ave', 'San Antonio', 'TX', '78210', '', 'el-luchador-bar-san-antonio-2'),
    ('Stout House- Alamo Ranch', '11911 ALAMO RANCH PKWY, STE 133', 'San Antonio', 'TX', '78253', 'http://www.stouthousesa.com/', 'stout-house-san-antonio-3'),
    ('Slackers', '7959 Fredericksburg Rd Suite 131', 'San Antonio', 'TX', '78229', '', 'slackers-sports-bar-san-antonio-2'),
    ('Oak Hills Tavern', '7920 Fredericksburg Rd', 'San Antonio', 'TX', '78229', 'https://www.oakhillstavern.com/', 'oak-hills-tavern-san-antonio'),
    ('90 Proof Bar & Grill', '11880 W. US Hwy 90 Ste.110', 'San Antonio', 'TX', '78245', 'https://90proofsa.com/', '90-proof-bar-and-grill-san-antonio'),
    ('Dad\'s Karaoke', '2615 Mossrock, San Antonio', 'San Antonio', 'TX', '78230', '', 'dads-karaoke-san-antonio'),
    ('Thirsty Camel Bar', '5307 McCullough Ave', 'San Antonio', 'TX', '78212', 'https://do210.com/venues/thirsty-camel', 'thirsty-camel-bar-and-lounge-olmos-park'),
    ('Sir Winston\'s Pub', '2522 Nacogdoches Road', 'San Antonio', 'TX', '78217', 'https://sirwinstonspub.wixsite.com/winstons', 'sir-winstons-san-antonio'),
    ('Kung Fu Saloon', '5531 N. Loop 1604 W.', 'San Antonio', 'TX', '78257', 'https://kungfusaloon.com/locations/san-antonio/', 'kung-fu-saloon-no-title'),
    ('The Martini Club', '8507 McCullough Ave Ste A9', 'San Antonio', 'TX', '78216', 'https://www.martiniclubsatx.com/', 'the-martini-club-san-antonio'),
    ('Hidden Tavern', '11407 West Avenue', 'San Antonio', 'TX', '78213', 'http://hiddentavern.com/', 'hidden-tavern-san-antonio');